Added images and readme file (index.md)
brainhackorg/school pull request #134
Opened 2022-08-05 20:47 UTC by dylansutterlin

Pull request to merge with my project template, images and description. Let me know if anything in the markdown formatting has gone wrong! Thank you

2022-08-16 16:33 UTC, me-pic requested changes
Please check some typos

2022-08-16 16:33 UTC, me-pic commented on content/en/project/decoding-pain-related-brain-activity/index.md
> +### Background
Please remove the empty sections from the template

2022-08-16 16:33 UTC, me-pic commented on content/en/project/decoding-pain-related-brain-activity/index.md
> +The dataset that will be used comes from Desmartaux et al., 2021 and is access restricted. It includes 24 participants (13 women and 11 males) and mean age is 26.9. Subjects participated to a fMRI sc
has restricted access

2022-08-16 16:33 UTC, me-pic commented on content/en/project/decoding-pain-related-brain-activity/index.md
> +* data :vPermission pending to give access to date (...)
typo

2022-08-16 16:33 UTC, me-pic commented on content/en/project/decoding-pain-related-brain-activity/index.md
> +* docs : A readme file descripbing the pipeline
typo

2022-08-16 16:33 UTC, me-pic commented on content/en/project/decoding-pain-related-brain-activity/index.md
> +* src : All the general function that can we reused wihout context
typo

2022-08-16 16:33 UTC, me-pic commented on content/en/project/decoding-pain-related-brain-activity/index.md
> +* A nifti masker was used to project the 3 dimmensional contrast maps to 1 dimension with the argument `(mask_strategy = 'whole-brain-template', standardize = True)`
typo dimensional

2022-08-16 16:33 UTC, me-pic commented on content/en/project/decoding-pain-related-brain-activity/index.md
> +* With the final model, all the coefficients were reprojected to the MNI space using `masker.inverse_transform()`. Since there were four classes, six different class comparisons can be made and the h
typo appears

2022-08-16 16:33 UTC, me-pic commented on content/en/project/decoding-pain-related-brain-activity/index.md
> +Thanks to all the instructors, espicially Marie-Eve and Francois who took the time to sit down with me and precise some concepts and shed some light on many topics such as the proper workflow, bebugg
debugging techniques,

2022-08-17 21:12 UTC, dylansutterlin commented
I pushed the requested changes!

2022-09-27 15:54 UTC, pbellec commented on content/en/project/decoding-pain-related-brain-activity/index.md
> +Link to Github page : <a href="https://github.com/dylansutterlin">
this should link to the github of the project, not a personal page.

2022-09-28 03:24 UTC, me-pic commented
@pbellec All my comments have been addressed. I found some typo but I guess that codespell will fix them

2022-09-28 10:35 UTC, pbellec commented
Thanks @me-pic merging...

2022-09-28 10:35 UTC, merged